# Generated by Django 4.0.1 on 2022-01-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_remove_user_role_user_is_student_user_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='Ученик'),
        ),
    ]
