# Generated by Django 4.0.1 on 2022-03-21 19:29
import json
import os

from django.db import migrations

JSON_PATH = 'authapp/json'


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r', encoding='utf-8') as f:
        return json.load(f)


def forwards_func(apps, schema_editor):
    languages = apps.get_model('authapp', 'StudyLanguage')
    languages_json = load_from_json('languages')
    for language in languages_json:
        languages.objects.create(**language)


class Migration(migrations.Migration):
    dependencies = [
        ('authapp', '0016_studylanguage_remove_user_language_user_language'),
    ]

    operations = [
        migrations.RunPython(code=forwards_func)
    ]
