# Generated by Django 4.0.1 on 2022-04-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0023_user_is_recruiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_crm',
            field=models.BooleanField(default=False, verbose_name='Из alfa/amo crm'),
        ),
    ]
