# Generated by Django 4.0.1 on 2022-01-20 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileapp', '0002_alter_subject_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'TH'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
    ]
