# Generated by Django 4.0.1 on 2022-03-22 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileapp', '0019_remove_managerrequestspassword_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Возраст обучения',
                'verbose_name_plural': 'Возраста обучения',
            },
        ),
        migrations.CreateModel(
            name='EnglishLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Уровень английского',
                'verbose_name_plural': 'Уровни английского',
            },
        ),
        migrations.CreateModel(
            name='EnglishSpecializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Специализация по английскому',
                'verbose_name_plural': 'Специализации по английскому',
            },
        ),
        migrations.CreateModel(
            name='MathSpecializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Специализация по математике',
                'verbose_name_plural': 'Специализации по математике',
            },
        ),
        migrations.CreateModel(
            name='TeacherMathSpecializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special', models.ManyToManyField(to='profileapp.MathSpecializations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Специализация по математике учителя',
                'verbose_name_plural': 'Специализации по математике учителей',
            },
        ),
        migrations.CreateModel(
            name='TeacherEnglishSpecializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special', models.ManyToManyField(to='profileapp.EnglishSpecializations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Специализация по английскому учителя',
                'verbose_name_plural': 'Специализации по английскому учителей',
            },
        ),
        migrations.CreateModel(
            name='TeacherEnglishLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ManyToManyField(to='profileapp.EnglishLevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уровень английского учителя',
                'verbose_name_plural': 'Уровни английского учителей',
            },
        ),
        migrations.CreateModel(
            name='TeacherAgeLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_learning', models.ManyToManyField(to='profileapp.AgeLearning')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Возраст обучения учителя',
                'verbose_name_plural': 'Возраста обучения',
            },
        ),
    ]
