# Generated by Django 4.0.1 on 2022-03-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0024_fill_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacheragelearning',
            options={'verbose_name': 'Возраст обучения учителя', 'verbose_name_plural': 'Возраста обучения учителя'},
        ),
    ]
