# Generated by Django 4.0.1 on 2022-03-29 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileapp', '0026_fill_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managertouser',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'is_stuff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='terenoi_manger', to=settings.AUTH_USER_MODEL, verbose_name='Менеджр'),
        ),
        migrations.AlterField(
            model_name='managertouser',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_stuff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='terenoi_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
