stages:
    - deploy

Deploy to stage:
    stage: deploy
    script:
        - cp $ENV_STAGE ./terenoi/.env
        - bash deploy.sh
#        - ln -s /home/gitlab-runner/media/ /home/gitlab-runner/projects/backend/
    only:
        - develop
    tags:
        - dev
