stages:
    - deploy

Deploy to stage:
    stage: deploy
    script:
        - cp $ENV_STAGE ./terenoi/.env
        - bash deploy.sh
        - ln -s /home/gitlab-runner/media/ /home/gitlab-runner/builds/-ZpcesB5/0/oscarbot/ternoi_back/terenoi/
    only:
        - develop
    tags:
        - dev
