stages:
    - deploy

Deploy to stage:
    stage: deploy
    script:
        - cp $ENV_STAGE .env
        - bash deploy.sh
        - ln -s /home/gitlab-runner/media/ /home/gitlab-runner/projects/back/
    only:
        - develop
    tags:
        - dev


Deploy to prod:
    stage: deploy
    script:
        - cp $ENV_PROD .env
        - bash deploy.sh
        - ln -s /home/gitlab-runner/media/ /home/gitlab-runner/projects/back/
    only:
        - main
    tags:
        - prod

