# Generated by Django 4.0.1 on 2022-04-21 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmoCRM', '0002_clients_leads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leads',
            options={'verbose_name': 'Сделки', 'verbose_name_plural': 'Сделка'},
        ),
        migrations.AlterField(
            model_name='leads',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='CustomerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_amo_funnel_status', models.BigIntegerField(blank=True, null=True, verbose_name='Айди статуса воронки в Амо')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название воронки')),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmoCRM.funnel', verbose_name='Воронка')),
            ],
            options={
                'verbose_name': 'Статусы покупателей',
                'verbose_name_plural': 'Статус покупателя',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amo_id', models.BigIntegerField(blank=True, null=True, verbose_name='Айди в Амо')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Ожидаемая сумма покупки')),
                ('next_date', models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемая дата следующей покупки.')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmoCRM.clients', verbose_name='Клиент')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmoCRM.customerstatus', verbose_name='Статус покупателя')),
            ],
            options={
                'verbose_name': 'Покупатели',
                'verbose_name_plural': 'Покупатель',
            },
        ),
    ]
