# Generated by Django 4.0.1 on 2022-04-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmoCRM', '0007_clients_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmoCRM.clients', verbose_name='Клиент'),
        ),
    ]
