# Generated by Django 4.0.1 on 2022-04-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmoCRM', '0008_alter_leads_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
    ]
