# Generated by Django 4.0.1 on 2022-02-21 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0007_referralpromo_from_user_alter_referralpromo_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(verbose_name='Ставка')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Ставка учителя',
                'verbose_name_plural': 'Ставка учителя',
            },
        ),
    ]
