# Generated by Django 4.0.1 on 2022-03-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_teacherrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypaymentstudent',
            name='debit',
            field=models.BooleanField(default=False, verbose_name='Списание'),
        ),
        migrations.AlterField(
            model_name='historypaymentstudent',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма зачисления или списания'),
        ),
        migrations.AlterField(
            model_name='historypaymentstudent',
            name='payment_date',
            field=models.DateTimeField(verbose_name='Дата и время зачисления или списания'),
        ),
    ]
