# Generated by Django 4.0.1 on 2022-03-05 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_alter_managerrequests_type'),
        ('finance', '0003_historypaymentstudent_debit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypaymentstudent',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='Урок'),
        ),
    ]
