# Generated by Django 4.0.1 on 2022-03-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_historypaymentstudent_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypaymentstudent',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к оплате'),
        ),
        migrations.AddField(
            model_name='historypaymentteacher',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к оплате'),
        ),
    ]
