# Generated by Django 4.0.1 on 2022-03-21 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0005_historypaymentstudent_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherBankData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Банк получателя')),
                ('bik', models.IntegerField(blank=True, null=True, verbose_name='БИК')),
                ('full_name', models.CharField(max_length=255, verbose_name='Получатель')),
                ('bill', models.IntegerField(verbose_name='Счет получателя')),
                ('card', models.BigIntegerField(blank=True, null=True, verbose_name='Номер карты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Реквизиты учителя',
                'verbose_name_plural': 'Реквизиты учителей',
            },
        ),
    ]
