# Generated by Django 4.0.1 on 2022-03-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_teacherbankdata_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherbankdata',
            old_name='full_name',
            new_name='full_teacher_name',
        ),
    ]
