# Generated by Django 4.0.1 on 2022-03-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_teacherbankdata_bik_alter_teacherbankdata_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypaymentteacher',
            name='is_enrollment',
            field=models.BooleanField(default=False, verbose_name='Зачисление'),
        ),
    ]
