# Generated by Django 4.0.1 on 2022-03-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_teacherbankdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherbankdata',
            name='card',
            field=models.TextField(blank=True, null=True, verbose_name='Номер карты'),
        ),
    ]
