# Generated by Django 4.0.1 on 2022-03-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_teacherbankdata_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypaymentstudent',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='student_invoices/', verbose_name='Квитанция'),
        ),
        migrations.AddField(
            model_name='historypaymentteacher',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='teacher_invoices/', verbose_name='Квитанция'),
        ),
    ]
