# Generated by Django 4.0.1 on 2022-12-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_historypaymentstudent_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherbalance',
            name='money_balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
    ]
