# Generated by Django 4.0.1 on 2023-02-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_teacherbalance_money_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('plan_type', models.CharField(choices=[('Индивидуальный', 'Индивидуальный'), ('Парный', 'Парный'), ('Групповой', 'Групповой')], default='Индивидуальный', max_length=50, verbose_name='Тип плана')),
                ('billing', models.CharField(choices=[('Поурочная', 'Поурочная'), ('Помесячная', 'Помесячная'), ('Недельная', 'Недельная')], default='Поурочная', max_length=50, verbose_name='Тарификация')),
                ('lesson_count', models.IntegerField(verbose_name='Кол-во уроков')),
                ('lesson_duration', models.IntegerField(verbose_name='Длительность урока, мин.')),
                ('lesson_cost', models.IntegerField(verbose_name='Цена за 1 урок')),
                ('subscription_cost', models.IntegerField(verbose_name='Стоимость абонемента')),
            ],
        ),
    ]
