# Generated by Django 4.0.1 on 2023-02-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_studentsubscription_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_methods', models.CharField(default='Kaspi pay', max_length=50, verbose_name='Способ оплаты')),
            ],
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='lesson_duration',
            field=models.IntegerField(verbose_name='Длительность урока, мин'),
        ),
        migrations.AddField(
            model_name='studentsubscription',
            name='payment_methods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.directorypaymentmethod'),
        ),
    ]
