# Generated by Django 4.0.1 on 2023-02-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_directorypaymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorypaymentmethod',
            name='payment_methods',
            field=models.CharField(choices=[('Kaspi pay', 'Kaspi pay'), ('Kaspi Tilek личный', 'Kaspi Tilek личный'), ('Серикболсын Сбер', 'Серикболсын Сбер'), ('Халык Тилек', 'Халык Тилек'), ('Киргизстан Нурсултан', 'Киргизстан Нурсултан'), ('Узбекистан Юлиана', 'Узбекистан Юлиана')], default='Kaspi pay', max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
