# Generated by Django 4.0.1 on 2023-02-08 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_directorypaymentmethod_payment_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Метод оплаты')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
            },
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='payment_methods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.paymentmethod', verbose_name='Метод оплаты'),
        ),
        migrations.DeleteModel(
            name='DirectoryPaymentMethod',
        ),
    ]
