# Generated by Django 4.0.1 on 2023-02-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная подписка'),
        ),
    ]
