# Generated by Django 4.0.1 on 2023-02-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_studentsubscription_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активная подписка'),
        ),
    ]
