# Generated by Django 4.0.1 on 2023-02-23 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0020_alter_studentsubscription_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubscription',
            name='student',
        ),
        migrations.AddField(
            model_name='studentsubscription',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
