# Generated by Django 4.0.1 on 2023-02-23 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0021_remove_studentsubscription_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='student',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
