# Generated by Django 4.0.1 on 2023-02-23 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0023_alter_studentsubscription_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbalance',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='balance_students', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
    ]
