# Generated by Django 4.0.1 on 2023-02-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_alter_studentbalance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbalance',
            name='money_balance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Баланс'),
        ),
    ]
