# Generated by Django 4.0.1 on 2022-02-02 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_alter_subject_user'),
        ('lessons', '0004_alter_lesson_student_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_homework',
            field=models.FileField(blank=True, null=True, upload_to='homework-for-lesson/', verbose_name='Домашнее задание к уроку'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_materials',
            field=models.FileField(blank=True, null=True, upload_to='materials-for-lesson/', verbose_name='Материалы к уроку'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(blank=True, limit_choices_to={'user': models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='profileapp.subject', verbose_name='Предмет'),
        ),
    ]
