# Generated by Django 4.0.1 on 2022-02-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_lesson_student_evaluation_and_more'),
        ('lessons', '0007_voximplantrecordlesson'),
    ]

    operations = [
    ]
