# Generated by Django 4.0.1 on 2022-02-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_lesson_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
    ]
