# Generated by Django 4.0.1 on 2022-02-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_lesson_transfer_date_alter_lesson_lesson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сроки сдачи домашнего задания'),
        ),
        migrations.AddField(
            model_name='lessonhomework',
            name='text_homework',
            field=models.TextField(blank=True, null=True, verbose_name='Текстовое домашнее задание'),
        ),
        migrations.AddField(
            model_name='lessonmaterials',
            name='text_material',
            field=models.TextField(blank=True, null=True, verbose_name='Текстовое поле для материалов и комментариев'),
        ),
        migrations.CreateModel(
            name='LessonRateHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Оценка домашнего задания')),
                ('rate_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к домашнему заданию')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='Урок')),
            ],
        ),
    ]
