# Generated by Django 4.0.1 on 2022-02-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_lesson_deadline_lessonhomework_text_homework_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonratehomework',
            options={'verbose_name': 'Оценки домашнего задания ученика', 'verbose_name_plural': 'Оценки домашнего задания'},
        ),
    ]
