# Generated by Django 4.0.1 on 2022-02-21 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0014_lesson_topic_alter_lesson_student_evaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_status',
            field=models.CharField(choices=[('SCH', 'Урок назначен'), ('REQ_RESCH', 'Запрос на перенос урока'), ('RESCH', 'Урок перенесен'), ('PRG', 'Урок идет'), ('DN', 'Урок проведен'), ('REQ_CNL', 'Запрос на отмену урока'), ('CNL', 'Урок отменен')], default='SCH', max_length=15, verbose_name='Статус урока'),
        ),
        migrations.CreateModel(
            name='ManagerRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('REQ_RESCH', 'Запрос на перенос урока'), ('RESCH', 'Урок перенесен'), ('REQ_CNL', 'Запрос на отмену урока'), ('CNL', 'Урок отменен')], max_length=15, null=True, verbose_name='Тип запроса')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Решен')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
