# Generated by Django 4.0.1 on 2022-03-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_weekdays'),
        ('lessons', '0022_schedule_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='count',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='near_meet',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='weekday',
        ),
        migrations.CreateModel(
            name='ScheduleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='Кол-во уроков')),
                ('near_meet', models.DateTimeField(blank=True, null=True, verbose_name='Ближайший урок')),
                ('shedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.schedule', verbose_name='Расписание')),
                ('weekday', models.ManyToManyField(to='settings.WeekDays', verbose_name='Дни недели')),
            ],
        ),
    ]
