# Generated by Django 4.0.1 on 2022-03-23 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0025_alter_teacheragelearning_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0026_lesson_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerRequestsRejectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к отказу от ученика')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Решен')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reject_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('new_teacher', models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reject_new_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Новый учитель')),
                ('old_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reject_old_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Старый учитель')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reject_student', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profileapp.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Запрос на изменение учителя у ученика',
                'verbose_name_plural': 'Запросы на изменение учителя у ученика',
            },
        ),
    ]
