# Generated by Django 4.0.1 on 2022-03-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0028_lesson_student_entry_date_lesson_teacher_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершенно'),
        ),
    ]
