# Generated by Django 4.0.1 on 2022-04-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0031_teacherworkhours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherworkhours',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='teacherworkhours',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец работы'),
        ),
        migrations.AddField(
            model_name='teacherworkhours',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало работы'),
        ),
    ]
