# Generated by Django 4.0.1 on 2022-04-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_weekdays_american_number'),
        ('lessons', '0032_remove_teacherworkhours_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherworkhours',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='teacherworkhours',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='teacherworkhours',
            name='weekday',
        ),
        migrations.AddField(
            model_name='teacherworkhours',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='TeacherWorkHoursSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало работы')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Конец работы')),
                ('teacher_work_hours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.teacherworkhours', verbose_name='Рабочие часы учителя')),
                ('weekday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.weekdays', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Настройки рабочих часов учителя',
                'verbose_name_plural': 'Настройки рабочих часов учителя',
            },
        ),
    ]
