# Generated by Django 4.0.1 on 2022-03-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_rateteachers_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityTimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('time_zone', models.CharField(max_length=15, verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Город и часовой пояс',
                'verbose_name_plural': 'Города и часовые пояса',
            },
        ),
    ]
