# Generated by Django 4.0.1 on 2022-03-12 17:39
import json
import os

from django.db import migrations

JSON_PATH = 'settings/json'


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r', encoding='utf-8') as f:
        return json.load(f)


def forwards_func(apps, schema_editor):
    weekdays = apps.get_model('settings', 'WeekDays')
    weekdays_json = load_from_json('weekdays')
    for weekday in weekdays_json:
        weekdays.objects.create(**weekday)


class Migration(migrations.Migration):
    dependencies = [
        ('settings', '0009_weekdays'),
    ]

    operations = [
        migrations.RunPython(code=forwards_func)
    ]
