# Generated by Django 4.0.1 on 2022-03-17 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_fill_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercity',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.citytimezone', verbose_name='Город проживания'),
        ),
    ]
