# Generated by Django 4.0.1 on 2022-04-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_fill_weekends'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoCRMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Токен для доступа')),
            ],
            options={
                'verbose_name': 'Токены дооступа к AmoCRM',
                'verbose_name_plural': 'Токен дооступа к AmoCRM',
            },
        ),
    ]
