# Generated by Django 4.0.1 on 2022-04-21 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_amo_funnel', models.BigIntegerField(blank=True, null=True, verbose_name='Айди воронки в Амо')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название воронки')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главная воронка')),
            ],
            options={
                'verbose_name': 'Воронки',
                'verbose_name_plural': 'Воронка',
            },
        ),
        migrations.CreateModel(
            name='FunnelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_amo_funnel_status', models.BigIntegerField(blank=True, null=True, verbose_name='Айди статуса воронки в Амо')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название воронки')),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmoCRM.funnel', verbose_name='Воронка')),
            ],
            options={
                'verbose_name': 'Статусы воронок',
                'verbose_name_plural': 'Статус воронки',
            },
        ),
    ]
