# Generated by Django 4.0.1 on 2022-04-21 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmoCRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amo_id', models.BigIntegerField(blank=True, null=True, verbose_name='Айди в Амо')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиент',
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amo_id', models.BigIntegerField(blank=True, null=True, verbose_name='Айди в Амо')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmoCRM.clients', verbose_name='Клиент')),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmoCRM.funnel', verbose_name='Воронка')),
                ('funnel_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmoCRM.funnelstatus', verbose_name='Статус воронки')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиент',
            },
        ),
    ]
