# Generated by Django 4.0.1 on 2022-04-21 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmoCRM', '0003_alter_leads_options_alter_leads_name_customerstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerstatus',
            old_name='id_amo_funnel_status',
            new_name='id_amo',
        ),
    ]
