# Generated by Django 4.0.1 on 2022-01-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_user_education_user_experience_user_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subject',
        ),
    ]
