# Generated by Django 4.0.1 on 2022-01-20 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_remove_user_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoxiAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voxi_username', models.CharField(max_length=150, unique=True, verbose_name='Логин Voxiplant')),
                ('voxi_display_name', models.CharField(max_length=150, verbose_name='Имя Voxiplant')),
                ('voxi_password', models.CharField(max_length=50, verbose_name='Пароль Voxiplant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
