# Generated by Django 4.0.1 on 2022-01-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_voxiaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voxiaccount',
            options={'verbose_name': 'Voxiplant Аккаунт', 'verbose_name_plural': 'Voxiplant Аккаунты'},
        ),
        migrations.AddField(
            model_name='voxiaccount',
            name='voxi_user_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='id пользователя Voxiplant'),
        ),
    ]
