# Generated by Django 4.0.1 on 2022-03-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_user_gender_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('R', 'Русский'), ('K', 'Казахстанский'), ('E', 'Английский')], max_length=10, null=True, verbose_name='Язык обучения'),
        ),
    ]
