# Generated by Django 4.0.1 on 2022-03-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('RU', 'Русский'), ('KZ', 'Казахстанский'), ('EN', 'Английский')], max_length=10, null=True, verbose_name='Язык обучения'),
        ),
    ]
