# Generated by Django 4.0.1 on 2022-03-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_alter_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Язык обучения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Язык обучения',
                'verbose_name_plural': 'Языки обучения',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.ManyToManyField(to='authapp.StudyLanguage', verbose_name='Язык обучения'),
        ),
    ]
