# Generated by Django 4.0.1 on 2022-03-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_alter_userstudylanguage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='english_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Elementary', 'Elementary'), ('Pre-intermediate', 'Pre-intermediate'), ('Intermediate', 'Intermediate'), ('Upper-intermediate', 'Upper-intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50, verbose_name='Уровень английского у ученика'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Класс ученика'),
        ),
    ]
