# Generated by Django 4.0.1 on 2022-04-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0024_user_is_crm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alfa_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Номер пользователя из alfa/amo crm'),
        ),
    ]
