# Generated by Django 4.0.1 on 2022-11-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0027_webinar_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='landing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хэш'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хэш'),
        ),
    ]
