# Generated by Django 4.0.1 on 2022-11-04 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0028_webinar_landing_webinar_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='ext_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PruffmeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.IntegerField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
                ('webinar_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('session', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
