# Generated by Django 4.0.1 on 2022-11-04 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0029_webinar_ext_id_pruffmeaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruffmeaccount',
            name='webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.webinar'),
        ),
    ]
