# Generated by Django 4.0.1 on 2022-11-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0031_webinar_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruffmeaccount',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
