# Generated by Django 4.0.1 on 2022-11-05 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0032_pruffmeaccount_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(blank=True, max_length=255, null=True)),
                ('webinar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.webinar')),
            ],
        ),
    ]
