# Generated by Django 4.0.1 on 2022-11-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0033_webinarrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoxiAccount',
        ),
    ]
