# Generated by Django 4.0.1 on 2022-11-30 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0034_delete_voxiaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название группы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('english_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Elementary', 'Elementary'), ('Pre-intermediate', 'Pre-intermediate'), ('Intermediate', 'Intermediate'), ('Upper-intermediate', 'Upper-intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50, verbose_name='Уровень английского')),
                ('status', models.CharField(choices=[('open', 'Идет набор'), ('lear', 'Обучается'), ('done', 'Завершена')], default='open', max_length=15, verbose_name='Статус')),
                ('alfa_id', models.BigIntegerField(blank=True, null=True, verbose_name='Номер из alfa crm')),
                ('students', models.ManyToManyField(related_name='group_students', to=settings.AUTH_USER_MODEL, verbose_name='Ученики')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный преподаватель')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
            },
        ),
    ]
