# Generated by Django 4.0.1 on 2022-12-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0036_user_crm_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='crm_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
