# Generated by Django 4.0.1 on 2023-01-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0038_alter_group_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='create_status',
            field=models.CharField(choices=[('normal', 'Обычное создание группы'), ('fast', 'Быстрое создание группы')], default='normal', max_length=25, verbose_name='Тип создания'),
        ),
    ]
