# Generated by Django 4.0.1 on 2023-01-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0038_alter_group_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Активный', 'Активный'), ('На паузе', 'На паузе'), ('Архивный', 'Архивный'), ('Отказ', 'Отказ')], default='Активный', max_length=8, verbose_name='Статус'),
        ),
    ]
