# Generated by Django 4.0.1 on 2023-01-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0039_group_create_status'),
        ('authapp', '0039_user_status'),
    ]

    operations = [
    ]
