# Generated by Django 4.0.1 on 2023-01-29 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0041_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalUserNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Дополнительный телефон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментраий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
