# Generated by Django 4.0.1 on 2023-01-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0042_additionalusernumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalusernumber',
            old_name='user',
            new_name='user_ref',
        ),
        migrations.AddField(
            model_name='user',
            name='additional_number',
            field=models.ManyToManyField(blank=True, null=True, to='authapp.AdditionalUserNumber', verbose_name='Дополнительные номера'),
        ),
    ]
