# Generated by Django 4.0.1 on 2023-01-31 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0040_merge_0039_group_create_status_0039_user_status'),
        ('authapp', '0043_rename_user_additionalusernumber_user_ref_and_more'),
    ]

    operations = [
    ]
