# Generated by Django 4.0.1 on 2023-02-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0051_user_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalusernumber',
            options={'verbose_name': 'Дполнительные номера'},
        ),
    ]
