# Generated by Django 4.0.1 on 2023-02-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0046_remove_schedule_lesson_duration_and_more'),
        ('finance', '0018_paymentmethod_and_more'),
        ('authapp', '0053_alter_user_is_student_alter_user_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='schedule',
        ),
        migrations.AddField(
            model_name='user',
            name='schedule',
            field=models.ManyToManyField(blank=True, null=True, to='lessons.ScheduleSettings', verbose_name='Расписания'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ManyToManyField(blank=True, null=True, to='finance.StudentSubscription', verbose_name='Подписки'),
        ),
    ]
