# Generated by Django 4.0.1 on 2023-02-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0054_remove_user_schedule_user_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
    ]
