# Generated by Django 4.0.1 on 2023-02-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0055_remove_user_schedule_remove_user_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='additional_user_number',
            field=models.ManyToManyField(blank=True, to='authapp.AdditionalUserNumber', verbose_name='Дополнительный номер'),
        ),
    ]
