# Generated by Django 4.0.1 on 2022-02-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_count', models.IntegerField(blank=True, null=True, verbose_name='Кол-во уроков для ученика')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Сумма выплаты для учителя')),
                ('currency', models.CharField(choices=[('KZT', 'KZT'), ('USD', 'USD')], default='KZT', max_length=5, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Реферальная система',
                'verbose_name_plural': 'Реферальная система',
            },
        ),
    ]
