# Generated by Django 4.0.1 on 2022-03-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0009_referralpromo_friend_is_used'),
        ('settings', '0002_referralsettings_friend_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(verbose_name='Ставка')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Ставка учителя за предмет',
                'verbose_name_plural': 'Ставка учителя за предмет',
            },
        ),
        migrations.CreateModel(
            name='DeadlineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_count', models.IntegerField(verbose_name='Кол-во дней')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Дедлайн для домашнего задания',
                'verbose_name_plural': 'Дедлайн для домашнего задания',
            },
        ),
    ]
