# Generated by Django 4.0.1 on 2022-03-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_rateteachers_deadlinesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rateteachers',
            options={'verbose_name': 'Ставка учителя по-умолчанию', 'verbose_name_plural': 'Ставки учителя по-умолчанию'},
        ),
    ]
