# Generated by Django 4.0.1 on 2022-03-07 12:47
import json
import os

from django.db import migrations

JSON_PATH = 'settings/json'


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r', encoding='utf-8') as f:
        return json.load(f)


def forwards_func(apps, schema_editor):
    cities = apps.get_model('settings', 'CityTimeZone')
    cities_json = load_from_json('cities')
    for city in cities_json:
        cities.objects.create(**city)


class Migration(migrations.Migration):
    dependencies = [
        ('settings', '0005_citytimezone'),
    ]

    operations = [
        migrations.RunPython(code=forwards_func)
    ]
