# Generated by Django 4.0.1 on 2022-03-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_usercity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercity',
            options={'verbose_name': 'Город пользователя', 'verbose_name_plural': 'Города пользователей'},
        ),
    ]
