# Generated by Django 4.0.1 on 2022-04-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_generalcontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekdays',
            name='american_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер дня(технический)'),
        ),
    ]
