# Generated by Django 4.0.1 on 2023-02-08 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='course_img/', verbose_name='Превью курса')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название курса')),
                ('time_duration', models.TimeField(verbose_name='Длительность курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('materials', models.FileField(blank=True, null=True, upload_to='materials-for-courses/', verbose_name='Полезные материалы к курсу')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
