# Generated by Django 4.0.1 on 2023-02-08 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(default=1, max_length=500, verbose_name='Название курса'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LessonCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='course_lesson_img/', verbose_name='Превью урока')),
                ('title', models.CharField(max_length=500, verbose_name='Название урока')),
                ('time_duration', models.TimeField(verbose_name='Длительность урока')),
                ('description', models.TextField(verbose_name='Описание урока')),
                ('video', models.FileField(upload_to='video-for-lesson/', verbose_name='Видео урока')),
                ('materials', models.FileField(blank=True, null=True, upload_to='materials-for-lesson/', verbose_name='Полезные материалы к уроку')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
