# Generated by Django 4.0.1 on 2022-02-25 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileapp', '0007_referralpromo_from_user_alter_referralpromo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terenoi_manger', to=settings.AUTH_USER_MODEL, verbose_name='Менеджр')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terenoi_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Менеджер-Пользователь',
                'verbose_name_plural': 'Менеджер-Пользователь',
            },
        ),
    ]
