# Generated by Django 4.0.1 on 2022-03-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_managertouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpromo',
            name='friend_is_used',
            field=models.BooleanField(default=False),
        ),
    ]
