# Generated by Django 4.0.1 on 2022-03-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0009_referralpromo_friend_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='questions',
            field=models.TextField(blank=True, null=True, verbose_name='Вопросы к предмету'),
        ),
    ]
