# Generated by Django 4.0.1 on 2022-03-09 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileapp', '0013_globaluserpurpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Интерес',
                'verbose_name_plural': 'Интересы',
            },
        ),
        migrations.AlterModelOptions(
            name='globaluserpurpose',
            options={'verbose_name': 'Цель ученика', 'verbose_name_plural': 'Цели учеников'},
        ),
        migrations.CreateModel(
            name='LanguageInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_language', models.CharField(choices=[('RU', 'Русский'), ('KZ', 'Казахстанский'), ('EN', 'Английский')], default='RU', max_length=10, verbose_name='Язык интерфейса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Язык интерфейса пользователя',
                'verbose_name_plural': 'Языки интерфейса пользователя',
            },
        ),
    ]
