# Generated by Django 4.0.1 on 2022-03-09 18:41
import json
import os

from django.db import migrations

JSON_PATH = 'profileapp/json'


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r', encoding='utf-8') as f:
        return json.load(f)


def forwards_func(apps, schema_editor):
    interests = apps.get_model('profileapp', 'Interests')
    interests_json = load_from_json('interests')
    for interest in interests_json:
        interests.objects.create(**interest)


class Migration(migrations.Migration):
    dependencies = [
        ('profileapp', '0014_interests_alter_globaluserpurpose_options_and_more'),
    ]

    operations = [
        migrations.RunPython(code=forwards_func)
    ]
