# Generated by Django 4.0.1 on 2022-03-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0016_userinterest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinterest',
            options={'verbose_name': 'Интерес пользователя', 'verbose_name_plural': 'Интересы пользователей'},
        ),
    ]
