# Generated by Django 4.0.1 on 2022-03-20 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileapp', '0017_alter_userinterest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerRequestsPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_password', models.CharField(max_length=50, verbose_name='Новый пароль')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата урока')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Решен')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос для изменения пароля',
                'verbose_name_plural': 'Запросы для изменения паролей',
            },
        ),
    ]
