# Generated by Django 4.0.1 on 2022-03-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0018_managerrequestspassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerrequestspassword',
            name='date',
        ),
    ]
