# Generated by Django 4.0.1 on 2022-03-22 01:04
import json
import os

from django.db import migrations

JSON_PATH = 'profileapp/json'


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r', encoding='utf-8') as f:
        return json.load(f)


def forwards_func(apps, schema_editor):
    ages = apps.get_model('profileapp', 'AgeLearning')
    ages_json = load_from_json('age')
    for age in ages_json:
        ages.objects.create(**age)


class Migration(migrations.Migration):
    dependencies = [
        ('profileapp', '0020_agelearning_englishlevel_englishspecializations_and_more'),
    ]

    operations = [
        migrations.RunPython(code=forwards_func)
    ]
