# Generated by Django 4.0.1 on 2022-03-22 01:14
import json
import os

from django.db import migrations

JSON_PATH = 'profileapp/json'


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r', encoding='utf-8') as f:
        return json.load(f)


def forwards_func(apps, schema_editor):
    levels = apps.get_model('profileapp', 'EnglishLevel')
    levels_json = load_from_json('level')
    for lvl in levels_json:
        levels.objects.create(**lvl)


class Migration(migrations.Migration):
    dependencies = [
        ('profileapp', '0023_fill_english'),
    ]

    operations = [
        migrations.RunPython(code=forwards_func)
    ]
