# Generated by Django 4.0.1 on 2022-04-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0028_alter_managertouser_manager_alter_managertouser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globaluserpurpose',
            name='purpose',
        ),
    ]
