# Generated by Django 4.0.1 on 2022-04-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0031_globaluserpurpose_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userparents',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО Родителя'),
        ),
    ]
