# Generated by Django 4.0.1 on 2023-03-06 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileapp', '0033_specialization_specializationitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specializationitems',
            options={'verbose_name': 'Пункт специализации учителя', 'verbose_name_plural': 'Пункты специализации учителя'},
        ),
        migrations.CreateModel(
            name='UserSpecializationItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.specializationitems', verbose_name='Пункт специализации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь-специлизация',
                'verbose_name_plural': 'Пользователи-специализации',
            },
        ),
    ]
