# Generated by Django 4.0.1 on 2022-01-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.DeleteModel(
            name='NotificationType',
        ),
    ]
