# Generated by Django 4.0.1 on 2022-03-31 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0012_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managernotification',
            options={'verbose_name': 'Уведомление для менеджера', 'verbose_name_plural': 'Уведомления для менеджеров'},
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='type',
            field=models.CharField(blank=True, choices=[('PD', 'Оплачено'), ('AP', 'Ожидает оплаты'), ('WD', 'Вывод средств'), ('EN_REF', 'Зачисление реферальной программы')], max_length=20, null=True, verbose_name='Тип уведомления'),
        ),
        migrations.CreateModel(
            name='HomeworkNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField(blank=True, null=True, verbose_name='Номер урока')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Оценка домашнего задания')),
                ('type', models.CharField(blank=True, choices=[('HM_ADD', 'Домашнее задание добавлено'), ('HM_CHK', 'Домашнее задание проверено'), ('HM_CHK_LOW', 'Домашнее задание проверено,оценка не удовлетворительная')], max_length=20, null=True, verbose_name='Тип уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление по домашнему заданию',
                'verbose_name_plural': 'Уведомления по домашним заданиям',
            },
        ),
    ]
