# Generated by Django 4.0.1 on 2022-04-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_homeworknotification_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonratenotification',
            name='type',
            field=models.CharField(blank=True, choices=[('LESS_RT_HGH', 'Урок оценен высоко'), ('LESS_RT_LOW', 'Урок оценен не удовлетворительно')], max_length=20, null=True, verbose_name='Тип уведомления'),
        ),
    ]
