# Generated by Django 4.0.1 on 2022-01-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_lesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('LSN_SCH', 'Урок назначен'), ('LSN_CMN', 'Урок скоро состоится'), ('LSN_PRG', 'Урок идет'), ('LSN_DN', 'Урок проведен'), ('LSN_CNL', 'Урок отменен')], max_length=20, null=True, verbose_name='Тип уведомления'),
        ),
    ]
