# Generated by Django 4.0.1 on 2022-02-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lesson_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер урока'),
        ),
    ]
