# Generated by Django 4.0.1 on 2022-03-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_paymentnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentnotification',
            name='type',
            field=models.CharField(blank=True, choices=[('PD', 'Оплачено'), ('AP', 'Ожидает оплаты')], max_length=20, null=True, verbose_name='Тип уведомления'),
        ),
    ]
