# Generated by Django 4.0.1 on 2022-03-31 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0011_alter_paymentnotification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление по уроку', 'verbose_name_plural': 'Уведомления по урокам'},
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='type',
            field=models.CharField(blank=True, choices=[('PD', 'Оплачено'), ('AP', 'Ожидает оплаты'), ('WD', 'Вывод средств')], max_length=20, null=True, verbose_name='Тип уведомления'),
        ),
        migrations.CreateModel(
            name='ManagerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('NU', 'Новый пользователь'), ('REQ_LSN_RESCH', 'Запрос на перенос урока'), ('REQ_LSN_CNL', 'Запрос на отмену урока'), ('REQ_RJC_U', 'Запрос на отказ от ученика'), ('REQ_CHN_PSS', 'Запрос на смену пароля')], max_length=20, null=True, verbose_name='Тип уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менежер')),
            ],
        ),
    ]
