# Generated by Django 4.0.1 on 2023-02-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_purchasedcoursesrequest'),
        ('notifications', '0017_alter_lessonratenotification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='managernotification',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='managernotification',
            name='type',
            field=models.CharField(blank=True, choices=[('NU', 'Новый пользователь'), ('REQ_LSN_RESCH', 'Запрос на перенос урока'), ('REQ_LSN_CNL', 'Запрос на отмену урока'), ('REQ_RJC_U', 'Запрос на отказ от ученика'), ('REQ_CHN_PSS', 'Запрос на смену пароля'), ('LESS_RT_HGH', 'Оценка за урок не удовлетворительная'), ('LESS_RT_HGH', 'Оценка за урок высокая'), ('REQ_BUY_CRS', 'Запрос на покупку курса')], max_length=20, null=True, verbose_name='Тип уведомления'),
        ),
    ]
