# Generated by Django 4.0.1 on 2023-02-10 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_courselikelist'),
        ('notifications', '0018_managernotification_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField(blank=True, null=True, verbose_name='Номер урока')),
                ('lesson_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата урока')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('type', models.CharField(blank=True, choices=[('CRS_OPEN', 'Курс открыт')], max_length=20, null=True, verbose_name='Тип уведомления')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='Курс')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Уведомлениe пользователя')),
            ],
            options={
                'verbose_name': 'Уведомление о доступе к курсу',
                'verbose_name_plural': 'Уведомления о доступах к курсам',
            },
        ),
    ]
