# Generated by Django 4.0.1 on 2022-01-20 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата урока')),
                ('teacher_status', models.BooleanField(default=False, verbose_name='Статус учителя')),
                ('student_status', models.BooleanField(default=False, verbose_name='Статус ученика')),
                ('lesson_status', models.CharField(choices=[('SCH', 'Урок назначен'), ('PRG', 'Урок идет'), ('DN', 'Урок проведен'), ('CNL', 'Урок отменен')], default='SCH', max_length=3, verbose_name='Статус урока')),
                ('record', models.URLField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_student', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
