# Generated by Django 4.0.1 on 2022-02-14 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_remove_lesson_lesson_homework_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoximplantRecordLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(verbose_name='Айди сессии звонка')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='Урок')),
            ],
        ),
    ]
