# Generated by Django 4.0.1 on 2022-02-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_merge_20220215_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voximplantrecordlesson',
            options={'verbose_name': 'Данные звонка', 'verbose_name_plural': 'Данные звонка'},
        ),
        migrations.AlterField(
            model_name='voximplantrecordlesson',
            name='session_id',
            field=models.BigIntegerField(verbose_name='Айди сессии звонка'),
        ),
    ]
