# Generated by Django 4.0.1 on 2022-02-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_remove_lesson_record_voximplantrecordlesson_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='transfer_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата переноса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_status',
            field=models.CharField(choices=[('SCH', 'Урок назначен'), ('REQ_RESCH', 'Запрос на перенос урока'), ('RESCH', 'Урок перенесен'), ('PRG', 'Урок идет'), ('DN', 'Урок проведен'), ('CNL', 'Урок отменен')], default='SCH', max_length=15, verbose_name='Статус урока'),
        ),
    ]
