# Generated by Django 4.0.1 on 2022-02-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_alter_lesson_lesson_status_managerrequests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerrequests',
            options={'verbose_name': 'Запрос для изменения урока', 'verbose_name_plural': 'Запросы для изменения уроков'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='transfer_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к переносу или отмене урока'),
        ),
        migrations.AddField(
            model_name='managerrequests',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к переносу или отмене урока'),
        ),
    ]
