# Generated by Django 4.0.1 on 2022-02-25 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0017_managerrequests_date_alter_managerrequests_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerrequests',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
    ]
