# Generated by Django 4.0.1 on 2022-02-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_managerrequests_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerrequests',
            name='type',
            field=models.CharField(blank=True, choices=[('REQ_RESCH', 'Запрос на перенос урока'), ('RESCH', 'Урок перенесен'), ('REQ_CNL', 'Запрос на отмену урока'), ('CNL', 'Урок отменен'), ('REJ', 'Запрос отклонен')], max_length=15, null=True, verbose_name='Тип запроса'),
        ),
    ]
