# Generated by Django 4.0.1 on 2022-03-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_schedule_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во уроков'),
        ),
    ]
