# Generated by Django 4.0.1 on 2022-03-20 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0025_remove_schedulesettings_weekday_schedule_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.schedule', verbose_name='Расписание'),
        ),
    ]
