# Generated by Django 4.0.1 on 2022-03-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0027_managerrequestsrejectteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='student_entry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата входа на урок ученика'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher_entry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата входа на урок учителя'),
        ),
    ]
