# Generated by Django 4.0.1 on 2022-04-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0029_schedule_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер урока'),
        ),
    ]
