# Generated by Django 4.0.1 on 2022-04-03 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0012_generalcontacts'),
        ('lessons', '0030_lesson_lesson_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherWorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершенно')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
                ('weekday', models.ManyToManyField(to='settings.WeekDays', verbose_name='Дни недели')),
            ],
            options={
                'verbose_name': 'Рабочие часы учителя',
                'verbose_name_plural': 'Рабочие часы учителя',
            },
        ),
    ]
