# Generated by Django 4.0.1 on 2022-11-17 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0033_remove_teacherworkhours_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='students',
            field=models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
