# Generated by Django 4.0.1 on 2022-11-29 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0038_lesson_student_evaluation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='student',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'is_student': True}, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.DeleteModel(
            name='VoximplantRecordLesson',
        ),
    ]
