# Generated by Django 4.0.1 on 2022-11-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0039_remove_schedule_student_alter_schedule_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
