# Generated by Django 4.0.1 on 2022-12-07 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0038_alter_group_teacher'),
        ('lessons', '0040_alter_schedule_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='students',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='students',
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_group', to='authapp.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_group', to='authapp.group', verbose_name='Группа'),
        ),
    ]
