# Generated by Django 4.0.1 on 2023-01-31 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0041_remove_lesson_students_remove_schedule_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonhomework',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_student', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
    ]
