# Generated by Django 4.0.1 on 2023-02-10 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0044_schedule_lesson_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='lesson_start',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='Начало урока'),
        ),
    ]
