# Generated by Django 4.0.1 on 2023-02-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0045_schedule_lesson_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='lesson_duration',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lesson_start',
        ),
        migrations.AddField(
            model_name='schedulesettings',
            name='lesson_duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Длительность урока, мин'),
        ),
    ]
