# Generated by Django 4.0.1 on 2023-02-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0046_remove_schedule_lesson_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='Длительность урока, мин'),
        ),
    ]
