# Generated by Django 4.0.1 on 2023-01-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_user_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
