# Generated by Django 4.0.1 on 2023-01-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalUserNumber',
        ),
    ]
